name: Release Type Action

description: GitHub Actions to do some actions based on release type.

author: technote-space

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    required: true
  BRANCH_NAME:
    description: Target branch name
    default: release/next
    required: true
  MINOR_UPDATE_TYPES:
    description: Minor update commit types
    default: feat
    required: false
  EXCLUDE_MESSAGES:
    description: Exclude messages
    required: false
  BREAKING_CHANGE_NOTES:
    description: Breaking change notes
    default: BREAKING CHANGE
    required: false
  TITLE_TEMPLATE:
    description: Title template
    default: 'feat: release ${NEXT_VERSION}'
    required: true
  MAJOR_LABEL:
    description: major release label
    default: 'Release: Major'
    required: false
  MINOR_LABEL:
    description: Minor release label
    default: 'Release: Minor'
    required: false
  PATCH_LABEL:
    description: Patch release label
    default: 'Release: Patch'
    required: false

branding:
  icon: 'git-pull-request'
  color: 'blue'

runs:
  using: node12
  main: lib/main.js
